# Generated by Django 3.0.5 on 2020-08-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterHost',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('protocol', models.CharField(default='http', max_length=20)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('cluster_host', models.OneToOneField(default='127.0.0.1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esmonitor.ClusterHost')),
                ('name', models.CharField(choices=[('node_stats', 'node_stats'), ('cluster_stats', 'cluster_stats')], max_length=200)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('json_content', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['-request_date'], name='esmonitor_s_request_34f2c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('cluster_host', 'request_date', 'name')},
        ),
    ]
