# Generated by Django 3.1 on 2020-08-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterhost',
            options={'verbose_name': 'Cluster Host', 'verbose_name_plural': 'Cluster Hosts'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Stats', 'verbose_name_plural': 'Stats'},
        ),
        migrations.AlterField(
            model_name='clusterhost',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clusterhost',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
