# Generated by Django 3.1 on 2020-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmonitor', '0002_auto_20200812_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
